
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - fusionpact-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - backend_data:/app/data
    restart: unless-stopped
    networks:
      - fusionpact-network

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    networks:
      - fusionpact-network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - fusionpact-network

volumes:
  backend_data:
  prometheus_data:
  grafana_data:

networks:
  fusionpact-network:
    driver: bridge
